services:
        discord-bot:
                build: .
                container_name: "discord-bot"
                volumes:
                        - .:/app
                command: "python main.py"
